basicform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('formapp.urls'))
]

formapp/urls.py
from django.urls import path


from . import views

app_name = 'formapp'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='HomePage'),
    path('FirstPage/', views.FirstPage, name='FirstPage'),
    path('SecondPage/', views.SecondPage, name='SecondPage'),
    path('ThirdPage/', views.ThirdPage, name='ThirdPage'),
]

formapp/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
    name = models.CharField(max_length=20, default='')
    email = models.EmailField(max_length=50, default='')
    phone = models.CharField(max_length=11, default='')
    message = models.CharField(max_length=200, default='')
    def __str__(self):
        return [self.name, self.email, self.phone, self.message]

formapp/forms.py
from django import forms

from .models import Message

class MessageForm(forms.ModelForm):
    name = forms.TextInput()
    email = forms.TextInput()
    phone = forms.TextInput()
    message = forms.TextInput()
    class Meta:
        model = Message
        fields = ('name', 'email', 'phone', 'message')

formapp/views.py
from django.shortcuts import render
from django.views import generic
from .models import Message
from .forms import MessageForm

# Create your views here.

from django.http import HttpResponse


class HomePageView(generic.ListView):
    template_name = 'formapp/HomePage.html'
    context_object_name = 'message_list'

    def get_queryset(self):
        return Message.objects.all()

def FirstPage(request):
    return render(request, 'formapp/FirstPage.html')


def SecondPage(request):
    return render(request, 'formapp/SecondPage.html')

def ThirdPage(request):
    context_object_name = 'message_list'
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'formapp/ThirdPage.html', {context_object_name: Message.objects.filter().order_by('pk')[:1], 'form': MessageForm()})
    else:
        form = MessageForm(request.POST)   
    return render(request, 'formapp/ThirdPage.html', {'form': form})

formapp/templates/formapp/FirstPage.html
{% extends 'formapp/SideBar.html' %} {% block content %}
<h1 class="w3-display-middle">1. Sayfa</h1>
{% endblock %}

formapp/templates/formapp/HomePage.html
{% extends 'formapp/SideBar.html' %} {% block content %} {% if message_list %}
{% for message in message_list %}
<ul class="w3-ul w3-border">
  <li><h2>{{forloop.counter}}. Mesaj</h2></li>
  <li><p>Name : {{message.name}}</p></li>
  <li><p>Email : {{message.email}}</p></li>
  <li><p>Phone : {{message.phone}}</p></li>
  <li><p>Message : {{message.message}}</p></li>
</ul>
{% endfor %} {% else %}
<p>No massage came yet</p>
{% endif %} {% endblock %}

formapp/templates/formapp/SecondPage.html
{% extends 'formapp/SideBar.html'%} {% block content %}
<div>
  <h1>Referanslar</h1>
  <div class="w3-panel w3-pale-blue w3-leftbar w3-bottombar w3-border-red">
    <h3>Python Kurulumu</h3>
    <a href="https://www.python.org/downloads/" target="_blank"
      >https://www.python.org/downloads/</a
    >
  </div>
  <div class="w3-panel w3-pale-blue w3-leftbar w3-bottombar w3-border-red">
    <h3>PostgreSQL kurulumu</h3>
    <a href="https://www.postgresql.org/" target="_blank"
      >https://www.postgresql.org/</a
    >
  </div>
  <div class="w3-panel w3-pale-blue w3-leftbar w3-bottombar w3-border-red">
    <h3>Psycopg kurulumu</h3>
    <a
      href="https://www.psycopg.org/psycopg3/docs/basic/install.html"
      target="_blank"
      >https://www.psycopg.org/psycopg3/docs/basic/install.html</a
    >
  </div>
  <div class="w3-panel w3-pale-blue w3-leftbar w3-bottombar w3-border-red">
    <h3>Django kurulumu</h3>
    <a
      href="https://docs.djangoproject.com/en/4.1/topics/install/"
      target="_blank"
      >https://docs.djangoproject.com/en/4.1/topics/install/</a
    >
  </div>
  <div class="w3-panel w3-pale-blue w3-leftbar w3-bottombar w3-border-red">
    <h3>Django kullanımının öğrenilmesi</h3>
    <a
      href="https://docs.djangoproject.com/en/4.1/intro/tutorial01/"
      target="_blank"
      >https://docs.djangoproject.com/en/4.1/intro/tutorial01/</a
    >
  </div>
  <div class="w3-panel w3-pale-blue w3-leftbar w3-bottombar w3-border-red">
    <h3>Database bağlantısı</h3>
    <a
      href="https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-DATABASES"
      target="_blank"
      >https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-DATABASES</a
    >
  </div>
  <div class="w3-panel w3-pale-blue w3-leftbar w3-bottombar w3-border-red">
    <h3>Jinja template kurulumu</h3>
    <a
      href="https://jinja.palletsprojects.com/en/3.1.x/intro/#installation"
      target="_blank"
      >https://jinja.palletsprojects.com/en/3.1.x/intro/#installation</a
    >
  </div>
  <div class="w3-panel w3-pale-blue w3-leftbar w3-bottombar w3-border-red">
    <h3>Django ile jinja kullanımı</h3>
    <a href="https://www.youtube.com/watch?v=PeMsRfSx_Ig" target="_blank"
      >https://www.youtube.com/watch?v=PeMsRfSx_Ig</a
    >
  </div>
  <div class="w3-panel w3-pale-blue w3-leftbar w3-bottombar w3-border-red">
    <h3>% block content % kullanımını öğrenmek için</h3>
    <a href="https://vegibit.com/django-block-content/" target="_blank"
      >https://vegibit.com/django-block-content/</a
    >
  </div>
</div>
{% endblock %}

formapp/templates/formapp/SideBar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="w3-sidebar w3-bar-block w3-blue" style="width: 20%">
      <a
        href="{% url 'formapp:HomePage' %}"
        class="w3-bar-item w3-button w3-border-bottom"
        >Anasayfa</a
      >
      <a
        href="{% url 'formapp:FirstPage' %}"
        class="w3-bar-item w3-button w3-border-bottom"
        >1. sayfa</a
      >
      <a
        href="{% url 'formapp:SecondPage' %}"
        class="w3-bar-item w3-button w3-border-bottom"
        >2. Sayfa</a
      >
      <a
        href="{% url 'formapp:ThirdPage' %}"
        class="w3-bar-item w3-button w3-border-bottom"
        >3. Sayfa</a
      >
    </div>
    <div style="margin-left: 20%">{% block content %} {% endblock%}</div>
  </body>
</html>

formapp/templates/formapp/ThirdPage.html
{% extends 'formapp/SideBar.html'%} {% block content %}
<form method="post" action="{% url 'formapp:ThirdPage' %}">
  {% csrf_token %}
  <div class="mb-3 form-label">{{ form.as_p }}</div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% if message_list %} {% for message in message_list %}
<ul class="w3-ul w3-border w3-margin-left">
  <li><h2>{{forloop.counter}}. Mesaj</h2></li>
  <li><p>Name : {{message.name}}</p></li>
  <li><p>Email : {{message.email}}</p></li>
  <li><p>Phone : {{message.phone}}</p></li>
  <li><p>Message : {{message.message}}</p></li>
</ul>
{% endfor %} {% else %}
<p>No massage came yet</p>
{% endif %} {% endblock %}